// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://PullToRefreshAppbar',
  'fluttercandies://PullToRefreshCandies',
  'fluttercandies://PullToRefreshChat',
  'fluttercandies://PullToRefreshHeader',
  'fluttercandies://PullToRefreshImage',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'Show how to use pull to refresh notification to build a pull refresh appbar'
  ///
  /// [name] : 'fluttercandies://PullToRefreshAppbar'
  ///
  /// [routeName] : 'PullToRefreshAppbar'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull refresh appbar'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesPullToRefreshAppbar =
      'fluttercandies://PullToRefreshAppbar';

  /// 'Show how to use pull to refresh notification to build a pull candies animation'
  ///
  /// [name] : 'fluttercandies://PullToRefreshCandies'
  ///
  /// [routeName] : 'PullToRefreshCandies'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull candies animation'
  ///
  /// [exts] : {group: Complex, order: 1}
  static const String fluttercandiesPullToRefreshCandies =
      'fluttercandies://PullToRefreshCandies';

  /// 'Show how to use pull to refresh notification for reverse list like chat list.'
  ///
  /// [name] : 'fluttercandies://PullToRefreshChat'
  ///
  /// [routeName] : 'PullToRefreshChat'
  ///
  /// [description] : 'Show how to use pull to refresh notification for reverse list like chat list.'
  ///
  /// [exts] : {group: Complex, order: 2}
  static const String fluttercandiesPullToRefreshChat =
      'fluttercandies://PullToRefreshChat';

  /// 'Show how to use pull to refresh notification to build a pull refresh header,and hide it on refresh done'
  ///
  /// [name] : 'fluttercandies://PullToRefreshHeader'
  ///
  /// [routeName] : 'PullToRefreshHeader'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull refresh header,and hide it on refresh done'
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String fluttercandiesPullToRefreshHeader =
      'fluttercandies://PullToRefreshHeader';

  /// 'Show how to use pull to refresh notification to build a pull refresh image'
  ///
  /// [name] : 'fluttercandies://PullToRefreshImage'
  ///
  /// [routeName] : 'PullToRefreshImage'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull refresh image'
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesPullToRefreshImage =
      'fluttercandies://PullToRefreshImage';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [arguments] : [keyValue]
  ///
  /// [argumentTypes] : [List<DemoRouteResult>]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
