// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://PullToRefreshAppbar',
  'fluttercandies://PullToRefreshCandies',
  'fluttercandies://PullToRefreshHeader',
  'fluttercandies://PullToRefreshImage',
  'fluttercandies://mainpage',
];

class Routes {
  const Routes._();

  /// 'Show how to use pull to refresh notification to build a pull refresh appbar'
  ///
  /// [name] : 'fluttercandies://PullToRefreshAppbar'
  ///
  /// [routeName] : 'PullToRefreshAppbar'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull refresh appbar'
  static const String fluttercandiesPullToRefreshAppbar =
      'fluttercandies://PullToRefreshAppbar';

  /// 'Show how to use pull to refresh notification to build a pull candies animation'
  ///
  /// [name] : 'fluttercandies://PullToRefreshCandies'
  ///
  /// [routeName] : 'PullToRefreshCandies'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull candies animation'
  static const String fluttercandiesPullToRefreshCandies =
      'fluttercandies://PullToRefreshCandies';

  /// 'Show how to use pull to refresh notification to build a pull refresh header,and hide it on refresh done'
  ///
  /// [name] : 'fluttercandies://PullToRefreshHeader'
  ///
  /// [routeName] : 'PullToRefreshHeader'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull refresh header,and hide it on refresh done'
  static const String fluttercandiesPullToRefreshHeader =
      'fluttercandies://PullToRefreshHeader';

  /// 'Show how to use pull to refresh notification to build a pull refresh image'
  ///
  /// [name] : 'fluttercandies://PullToRefreshImage'
  ///
  /// [routeName] : 'PullToRefreshImage'
  ///
  /// [description] : 'Show how to use pull to refresh notification to build a pull refresh image'
  static const String fluttercandiesPullToRefreshImage =
      'fluttercandies://PullToRefreshImage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';
}
