// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';
import 'pages/main_page.dart';
import 'pages/pull_to_refresh_appbar.dart';
import 'pages/pull_to_refresh_header.dart';
import 'pages/pull_to_refresh_image.dart';

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case "fluttercandies://mainpage":
      return RouteResult(
        widget: MainPage(),
        routeName: "MainPage",
      );
    case "fluttercandies://PullToRefreshAppbar":
      return RouteResult(
        widget: PullToRefreshAppbar(),
        routeName: "PullToRefreshAppbar",
        description:
            "Show how to use pull to refresh notification to build a pull refresh appbar",
      );
    case "fluttercandies://PullToRefreshHeader":
      return RouteResult(
        widget: PullToRefreshHeader(),
        routeName: "PullToRefreshHeader",
        description:
            "Show how to use pull to refresh notification to build a pull refresh header,and hide it on refresh done",
      );
    case "fluttercandies://PullToRefreshImage":
      return RouteResult(
        widget: PullToRefreshImage(),
        routeName: "PullToRefreshImage",
        description:
            "Show how to use pull to refresh notification to build a pull refresh image",
      );
    default:
      return RouteResult();
  }
}

class RouteResult {
  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  const RouteResult(
      {this.widget,
      this.showStatusBar = true,
      this.routeName = '',
      this.pageRouteType,
      this.description = ''});
}

enum PageRouteType { material, cupertino, transparent }

List<String> routeNames = [
  "fluttercandies://mainpage",
  "fluttercandies://PullToRefreshAppbar",
  "fluttercandies://PullToRefreshHeader",
  "fluttercandies://PullToRefreshImage"
];
